### ISSUE TITLE
8 MHz Arduino and SDI12 LIbrary

### ISSUE THREAD

**Issue by JustinWhitaker** [EnviroDIY/Arduino-SDI-12#12]
I have been using your library for some remote soil moisture sensor stations for our strawberry nursery stock production.  I'm using the Arduino Pro Mini 5V/16MHz versions and Decagon GS3 soil moisture sensors and everything is working great.  I want to redesign my sensor stations to be a little bit smaller and less power hungry (i.e. smaller solar panel, less battery capacity, etc) so I started testing the Arduino Pro Mini 3.3V/8MHz versions and the SDI12 communications stopped working.  I'm guessing it has something to do with the serial timing when moving from a 16 MHz device to an 8 MHz device, but I'm not familiar enough with the serial communication programming to know where to look or how to modify it to work at 8 MHz.  Could your library be modified to work at 8 MHz?  My initial thought was to double the SPACING constant since the speed is cut in half...am I even on the right track?

Thanks for your help in advance and thank you for making such a wonderful open-source SDI12 library in the first place.

PS - I emailed you also, but this seemed like a better place to ask my question...sorry for the double-post/email.

**Comment by shmrymbd** [comment]
hi sorry to ask. if my sensor is powered by 12V .. what is the signal output? +12V.. i am using arduino nano + hydra probe.. cant communicate. thanks

**Comment by Kevin-M-Smith** [comment]
Hi @shmrymbd, 

The output from SDI-12 probes is a binary serial output between 0-5v. The output is not an analog signal. Please see the latest specification here: http://sdi-12.org/current%20specification/SDI-12_version-1_4-August-10-2016.pdf

Best,
Kevin
